### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by tonmanayo** [Kbam7/42sh#19]
I think when you add the string to a list there is a memory leak, run the terminal and exit using the "exit" command and we seem to be getting a loss of 8,426 bytes

**Comment by Kbam7** [comment]
This is the output i got from running `valgrind --leak-check=full --track-origins=yes ./42sh -up` and then exiting.
[out3.txt](https://github.com/Kbam7/42sh/files/442583/out3.txt)

**Comment by tonmanayo** [comment]
found the memory leak, going to try fix it now, its located in init.c line 70   ft_set(1, "42SH_PID", tmpstr, s);

not to sure what is going on here

**Comment by tonmanayo** [comment]
comment it out and seg fault on exit

**Comment by tonmanayo** [comment]
nop found out that isnt the problem.

**Comment by Kbam7** [comment]
There shouldnt be a problem there. . . im not picking anything up on my system. So when i get to school again i will test on the Mac's. But for now lets not change anything cuz its working great on my side as is.

**Comment by Kbam7** [comment]
Also, line 70 in init.c is for storing the parent process ID so that we can exit a child process without setting the terminal attributes back to the default settings. There probably is a better way to do it. Like adding the PID's to an array or something and then just checking if the current PID is position '0' in the array. If it is, then do a full exit otherwise just free memory and kill the process.

**Comment by Kbam7** [comment]
Im actually going to open that as a separate issue because its actually quite important that i find a better solution. If someone removes `42SH_PID` from the env vars then the terminal will not exit correctly from a child process.
