### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by tonmanayo** [Kbam7/42sh#27]
unset env and env

**Comment by Kbam7** [comment]
Please provide more information . . . Like a print out or something. If you run a command and add "&> file.txt" it will write STDOUT and STDERR to the fille. That way you can actually show me where and what the problem is . . . I dont have any issues on my side, so how are you testing these functions?

**Comment by Kbam7** [comment]
at school unsetenv has an invalid write of size 8 at ft_unsetenv() - remove_var()

**Comment by Kbam7** [comment]
Fixed read error in unsetenv,
