### ISSUE TITLE
pipes

### ISSUE THREAD

**Issue by tonmanayo** [Kbam7/42sh#65]
ls > test.txt | cat -e test.txt

**Comment by Kbam7** [comment]
@tonmanayo :  Okay so this is super weird. . . i've tested this on my Laptop and the results are rather interesting. . . When using Bash(Linux shell, not ours) and i run `ls > test.txt | cat -e test.txt` for the first time, nothing happens. I can tell that both functions executed properly because there is no error message. For example, if you have `ls > test.txt | cat -e test55.txt`, it will write the `ls` to `test.txt` and then `cat` will produce an error saying `"'test55.txt' not found"`. That is obviously the expected output and when i run our shell with `ls > test.txt | cat -e test55.txt`, its exactly the same outcome. Okay cool, so now back to the original command, `ls > test.txt | cat -e test.txt`. With this command, it really depends on how fast `ls` can write to the file. When I test this command with Bash(Linux), i get intermittent results. Sometimes `cat -e test.txt` reads `test.txt` at the right time, other times it reads the file before `ls` has written to it, thus the reason nothing happens when you execute it sometimes. If the was an error, it would be printed. So the `ls > test.txt` part definitely works and `cat -e test.txt` part definitely works. Its just that sometimes `cat` will read the file directly after its been created(or truncated if the file already exists) and other times it will read the file after `ls` has written to the file. . . .please run some test and see if they coincide. Below is a screen shot of Bash executing the command. You will see its intermittent. 

BASH:
![bash](https://cloud.githubusercontent.com/assets/12624041/18379391/9e108f6e-7672-11e6-925b-88491b667e95.png)

OURS:
![ours](https://cloud.githubusercontent.com/assets/12624041/18379756/66cceb90-7674-11e6-8403-73cd5e9d42aa.png)

**Comment by tonmanayo** [comment]
exactly what you said, when the file is being created the first time cat doesnt work, but once the file has already been created it seems to work, i ran the 

![screen shot 2016-09-09 at 1 26 41 pm](https://cloud.githubusercontent.com/assets/18025339/18385453/16e40a7e-7691-11e6-8613-5eab826643b7.png)

working very weirdly only worked the third time after executing

**Comment by tonmanayo** [comment]
in iterm this command works ls > test.txt | cat -e
no file at the end
